### ISSUE TITLE
Write EKS cluster name to issue title or description

### ISSUE THREAD

**Issue by willdavsmith** [radius-project/samples#1003]
If the eshop-aws tests fail at the delete-eks-cluster step, we should write the EKS cluster name to the issue title or description for ease of debugging. Today, the on-call engineer has to manually search and filter to find how the test failed and track it in the AWS console.

[AB#11361](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/11361)

**Comment by willdavsmith** [comment]
we could also mark it as aws, azure, or containers eshop failed

**Comment by ytimocin** [comment]
Done via https://github.com/radius-project/samples/pull/1360.
