### ISSUE TITLE
Delete AWS Resources step sometimes fails if job is cancelled

### ISSUE THREAD

**Issue by willdavsmith** [radius-project/samples#1017]
Sometimes, if the Test Samples workflow runs and is cancelled, something will cause the "Delete AWS Resources" step to get stuck in an infinite loop and cancel:

<img width="1492" alt="image" src="https://github.com/radius-project/samples/assets/32342549/64a3654d-7e8b-4182-af02-ff0ecd45e4f6">

We could try adding the `cancelled()` condition here or making resource cleanups part of a different job.

[AB#11549](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/11549)

**Comment by ytimocin** [comment]
I updated this step to only run if the `Deploy App` step is successful and if Cancel Workflow is not called.

**Comment by ytimocin** [comment]
Continuing the discussion here: #1009.
