### ISSUE TITLE
Fix sample failures with name resolution error

### ISSUE THREAD

**Issue by nithyatsu** [radius-project/samples#1030]
We have multiple failures with below logs.
Web application is ready: http://localhost/
Error text: "Failed to load resource: the server responded with a status of 404 (Not Found)"
Error text: "Failed to load resource: the server responded with a status of 404 (Not Found)"
Error text: "Failed to load resource: the server responded with a status of 500 (Internal Server Error)"
Error text: "[2024-03-23T15:50:44.663Z] Error: Failed to complete negotiation with the server: Error"
Error text: "[2024-03-23T15:50:44.666Z] Error: Failed to start the connection: Error"
Error text: "Failed to load resource: net::ERR_NAME_NOT_RESOLVED"
 
Explore and fix tests to avoid this failure.

[AB#11642](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/11642)

**Comment by nicolejms** [comment]
regression from discovery feature changes.

**Comment by ytimocin** [comment]
This should have been fixed via #1360. Closing this for now and will watch out for this error. Will reopen this issue if necessary.
