### ISSUE TITLE
`Error requesting catalog products, please try later on` error message in eShop

### ISSUE THREAD

**Issue by ytimocin** [radius-project/samples#1545]
### Steps to reproduce (required)
1. Deploy eShop on Containers (This error is mostly happening in eShop on Containers)
2. Go to the main page of the application
3. See that the list of products is not visible and you have the error message: **Error requesting catalog products, please try later on**

### Observed behavior (required)
In UI tests that run every day, I have seen multiple instances of catalog not loading. This is causing, especially, eShop on Containers to fail.

### Desired behavior (required)
Catalog and all the products should be visible.

### Workaround (optional)
Rerunning the tests works most of the time.

## System information
Tests run on ubuntu VMs.

### rad Version (required)
0.33

### Operating system (required)
Ubuntu

## Additional context
**Please see the video created by the failing test itself:**
[video.webm](https://github.com/radius-project/samples/assets/5220939/48d55d19-638a-47a7-aafe-eb447f9dbc78)

[AB#12328](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/12328)

**Comment by sylvainsf** [comment]
Rather than fix the e-shop regression we should update the test to not care about this area of the UI if there's another area that is testing the connection to the catalog database. If it is the only one, maybe we should change it to a retry on long running only?

**Comment by ytimocin** [comment]
In the long running test cluster, we don't run the samples repo UI tests. If we would like to do that, we will have to invest some time in designing and implementing that part.

If you check this [run](https://github.com/radius-project/samples/actions/runs/9005374482), you will see that 3 out of 10 times the test failed with the products not loading.

I have an option of reloading the page **n** (like 5 or 10) times and if the catalog still is not available then I can skip the UI tests for the catalog. Because I know that this is not due to the UI tests but the application itself.

I'd like to get your ideas on this approach please. cc/ @sylvainsf @rynowak @kachawla

**Comment by rynowak** [comment]
My question is similar to @sylvainsf's. 

This is obviously a bug in the sample code, or a minor mistake in how we "radified" the sample. Is it worth our time to investigate and fix this issue? More directly, if we skipped [this part](https://github.com/radius-project/samples/blob/v0.33/playwright/tests/eshop/eshop.app.spec.ts#L77-L82) of the test, is it still a good test?

I think we're trying to balance the value of the test vs the cost of investigating bugs in the sample code.

**Comment by ytimocin** [comment]
I think what I am going to do here is that if the catalog loads successfully then I am going to run the rest of the tests. And, if not, I will log the issue and just exit the test.

**Comment by ytimocin** [comment]
Please see this PR: https://github.com/radius-project/samples/pull/1548.

**Comment by ytimocin** [comment]
If the catalog loads successfully then we run the rest of the tests which starts here: https://github.com/radius-project/samples/blob/v0.33/playwright/tests/eshop/eshop.app.spec.ts#L132.

If it doesn't load successfully, we do a console logging and exit the UI tests: https://github.com/radius-project/samples/blob/v0.33/playwright/tests/eshop/eshop.app.spec.ts#L124-L129.

This means that we are not investigating the catalog issue further here. **What is the catalog issue?** Sometimes the catalog is not loading properly. Application code must be checked further for this.

cc/ @sylvainsf @rynowak
