### ISSUE TITLE
"unknown flag: --client-id" error configuring cloud credentials

### ISSUE THREAD

**Issue by vishwahiremat** [radius-project/samples#1577]
### Steps to reproduce (required)
"unknown flag: --client-id" error configuring cloud credentials was seen on the samples tests workflow with release/0.34 branch.

### Observed behavior (required)
the issue is seen only when the workflow is run on the release/0.34 branch, its because of the cli changes we added as part of workload identity. It seems that workflow is run is the release/0.34 branch but radius version used is "edge" is the reason for this failure. After release/0.35 release workflow is not run on release/0.34 and not seeing this issue anymore, we need to fix this because we may see similar failures in the future if there are any breaking changes.

### Desired behavior (required)
workflow to run without any issues.

### rad Version (required)
edge

## Additional context

[AB#12611](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/12611)

**Comment by sylvainsf** [comment]
Is this resolved now that the release has shipped? There was an intentionally breaking change to the command which cause this.

**Comment by ytimocin** [comment]
Yes, it did @sylvainsf. Closing this issue.

**Comment by vishwahiremat** [comment]
This issue got resolved after the release was shipped, but its also more of general issue as well that we may encounter in the future when we may have breaking changes in edge. so i have created a general issue to track
 it https://github.com/radius-project/samples/issues/1578
