### ISSUE TITLE
Update rad download version in samples tests workflow

### ISSUE THREAD

**Issue by vishwahiremat** [radius-project/samples#1578]
Today we run scheduled samples workflow on the release branch but the radius version downloaded as part of the workflow default to edge. which mean if there are breaking changes in edge the pipeline runs starts failing until next release is out. [Here](https://github.com/radius-project/samples/actions/runs/9597025520/job/26465204496) is an example of the issue we came across when we had breaking changes in 0.35 and workflow on 0.34 started failing until we have 0.35 release out.

Proposed Solution:
Update the `Download rad cli` step to download the release version when workflow is running on a release branch.

**Comment by nicolejms** [comment]
Change in samples test workflow to pull correct version

**Comment by willdavsmith** [comment]
should be fixed by: https://github.com/radius-project/samples/commit/efa2f1ae70b2602836c3234eb5072fddd0ae808a
