### ISSUE TITLE
Fix upmerge samples to edge workflow

### ISSUE THREAD

**Issue by sk593** [radius-project/samples#1632]
### Steps to reproduce (required)
The upmerge samples to edge workflow fails when there's nothing to commit. This is okay since there were technically no changes but the workflow should still pass in this case 

https://github.com/radius-project/samples/actions/workflows/upmerge.yaml

## Additional context

[AB#12892](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/12892)

**Comment by brooke-hamilton** [comment]
@sk593 is the desired behavior that the workflow should complete without creating a PR if there are no changes to commit?

**Comment by sk593** [comment]
> @sk593 is the desired behavior that the workflow should complete without creating a PR if there are no changes to commit?

yup! the upmerge workflow should keep edge up to date with the current release branch. so if there are no changes, there's no need to create a PR
