### ISSUE TITLE
Add issue bot automation to the samples repo

### ISSUE THREAD

**Issue by brooke-hamilton** [radius-project/samples#1641]
## Overview of feature request

Add the ability to perform automation actions in issue comments, especially `/assign`. Currently, the `/assign` action is only available in the `radius` repo. 

## Acceptance criteria

- A commenter can reply to an issue in this repo using the `/assign` command.
- There is an established pattern for enabling the `/assign` command in other repos.
- The pattern allows additional commands to be added.
- The pattern allows commands to be enabled in any repo under `radius-project` with minimal configuration.
- Additional issues are created to enable `/assign` in other public repos under `radius-project` where appropriate.

## Additional context

The `/assign` command is enabled in these files in the `radius-project/radius` repository:
- `.github/workflows/radius-bot.yaml`
- `.github/scripts/radius-bot.js`

We need a way to enable the same automation in all `radius-project` repos without copy/pasting these files to all repos.

[AB#12906](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/12906)

**Comment by kachawla** [comment]
Added in https://github.com/radius-project/samples/pull/1746, and just tested on this issue (see above).
