### ISSUE TITLE
Add signoff to `Upmerge samples to edge` workflow

### ISSUE THREAD

**Issue by willdavsmith** [radius-project/samples#1884]
The [`Upmerge samples to edge`](https://github.com/radius-project/samples/actions/workflows/upmerge.yaml) workflow does not include a signoff message in the commit: https://github.com/radius-project/samples/blob/f92e009a248f05f3511c49e483259e89de48f2d1/.github/workflows/upmerge.yaml#L65

This causes DCO to fail during the release process. We should add a signoff flag to the `git merge` command.
 

[AB#13662](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/13662)

**Comment by ytimocin** [comment]
Closing this now @willdavsmith. You can re-open if it is not fixed already.

**Comment by kachawla** [comment]
This hasn't been fixed yet, re-opening and removing triage label.
