### ISSUE TITLE
Codespaces env - kubernetes not installed

### ISSUE THREAD

**Issue by lakshmimsft** [radius-project/samples#617]
Reproducing steps: 
I click https://codespaces.new/radius-project/samples to startup a codespaces env.
I'm in codespaces env. I see that radius is installed, running rad version gives v0.26.3  but i do not see kubernetes installed.
kubectl get pods -A results in errors indicating cluster is not installed.

Request to review if this behaviour is as expected or if we do want codespaces env with a cluster pre-installed.

[AB#9824](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/9824)

**Comment by jasonviviano** [comment]
Fixed, on branch `v0.26`
