### ISSUE TITLE
Failed to pull and unpack image ghcr.io/radius-project/tutorial/webapp:edge in Getting Started

### ISSUE THREAD

**Issue by pdebruin** [radius-project/samples#639]
Steps to reproduce: 
* Follow these instructions https://docs.radapp.io/getting-started/
* rad install works
* rad init works 
@pdebruin ➜ /workspaces/samples/radius-demo (v0.26) $ ll
total 16
drwxrwxrwx+ 3 codespace codespace 4096 Oct 19 07:22 ./
drwxrwxrwx+ 8 codespace root      4096 Oct 19 07:21 ../
drwxr-xr-x+ 2 codespace codespace 4096 Oct 19 07:22 .rad/
-rw-r--r--  1 codespace codespace  344 Oct 19 07:22 app.bicep
@pdebruin ➜ /workspaces/samples/radius-demo (v0.26) $ cat app.bicep 
import radius as radius
param application string

resource demo 'Applications.Core/containers@2023-10-01-preview' = {
  name: 'demo'
  properties: {
    application: application
    container: {
      image: 'ghcr.io/radius-project/tutorial/webapp:edge'
      ports: {
        web: {
          containerPort: 3000
        }
      }
    }
  }
}
* rad run app.bicep fails
Building app.bicep...
Deploying template 'app.bicep' for application 'radius-demo' and environment 'default' from workspace 'default'...

Deployment In Progress... 

..                   demo            Applications.Core/containers
Error: {
  "code": "DeploymentFailed",
  "message": "At least one resource deployment operation failed. Please see the details for the specific operation that failed.",
  "target": "/planes/radius/local/resourceGroups/default/providers/Microsoft.Resources/deployments/rad-deploy-e2d84e71-1278-4004-a8e3-83683a79db5e",
  "details": [
    {
      "code": "ResourceDeploymentFailure",
      "message": "Failed",
      "target": "/planes/radius/local/resourceGroups/default/providers/Applications.Core/containers/demo",
      "details": [
        {
          "code": "Internal",
          "message": "Container state is 'Waiting' Reason: ErrImagePull, Message: rpc error: code = Unknown desc = failed to pull and unpack image \"ghcr.io/radius-project/tutorial/webapp:edge\": failed to resolve reference \"ghcr.io/radius-project/tutorial/webapp:edge\": failed to authorize: failed to fetch anonymous token: unexpected status from GET request to https://ghcr.io/token?scope=repository%3Aradius-project%2Ftutorial%2Fwebapp%3Apull\u0026service=ghcr.io: 403 Forbidden"
        }
      ]
    }
  ]
}

TraceId:  9e617855686561b46da3adcd885b15dd

Workaround:
* Manually update app.bicep to refer image to 'radius.azurecr.io/samples/demo:latest' instead.

Hope this helps. Have a RAD time 😎

[AB#9858](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/9858)

**Comment by h2floh** [comment]
+1

I had problems with ghcr.io when I pushed a freely labeled image to it, which didn't corresponded to GitHub OwnerName scheme. For the docker image in this case org/repo `radius-project/tutorial` doesn't exist and might cause the issue even if the image with that name was previously was pushed to it. I also having problems with the `webapp:edge` reference.

**Comment by AaronCrawfis** [comment]
Thanks @pdebruin for the report! I got a PR in to fix this issue: https://github.com/radius-project/radius/pull/6520

I've also manually pushed a new tag so it can be pulled from the existing code.

Please reopen if you hit an additional issues
