### ISSUE TITLE
workflow should be updated to use the built sample images for testing.

### ISSUE THREAD

**Issue by nithyatsu** [radius-project/samples#725]
We currently have build and test workflows that run independently. Because of this, while we test the radius functionality, we still use the older samples code. we should integrate the 2 workflows such that the images built in the PR gets used for testing. 

[AB#9979](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/9979)

**Comment by shalabhms** [comment]
triage:  decided to fix this as priority in next Sprint.

**Comment by nicolejms** [comment]
ADO item is closed
