### ISSUE TITLE
dapr sample tests failing step: "Wait for all pods to be ready"

### ISSUE THREAD

**Issue by willdavsmith** [radius-project/samples#773]
The dapr sample tests fail in the  "Wait for all pods to be ready" step. it looks like pods/backend-749f6f94db-57ncq is in Terminating (1/2) state.

```
Run namespace="default-dapr"
pod/backend-5bd4c5745b-b7dpg condition met
pod/frontend-ddcd964db-7lcbm condition met
error: timed out waiting for the condition on pods/backend-749f6f94db-57ncq
```

[AB#10046](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/10046)

**Comment by willdavsmith** [comment]
This works locally but not in CI

**Comment by AaronCrawfis** [comment]
Fixed as part of https://github.com/radius-project/samples/pull/843 and https://github.com/radius-project/samples/pull/817.
