### ISSUE TITLE
`The maximum number of VPCs has been reached` error in the samples tests

### ISSUE THREAD

**Issue by ytimocin** [radius-project/samples#864]
Getting `maximum number of VPCs has been reached` error in test runs.

Example: https://github.com/radius-project/samples/actions/runs/6996535129/job/19032519197.

[AB#10539](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/10539)

**Comment by willdavsmith** [comment]
Should be fixed by https://github.com/radius-project/samples/pull/843

**Comment by shalabhms** [comment]
@lakshmimsft , are we still observing these failures in the samples repo ?

**Comment by lakshmimsft** [comment]
nope, nothing this week. Closing this issue.
