### ISSUE TITLE
EKS cluster not deleted if rad not installed

### ISSUE THREAD

**Issue by AaronCrawfis** [radius-project/samples#868]
Today we first uninstall Radius and then delete the EKS cluster. This can cause issues if rad was never installed. See https://github.com/radius-project/samples/actions/runs/7008834358/job/19065990928 for more information.

We either need to remove the uninstall command (I'm not sure why we need this) or we need to separate out these steps so uninstall is conditional on install, and EKS delete is conditional on the EKS cluster being created.

[AB#10540](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/10540)

**Comment by ytimocin** [comment]
Done via https://github.com/radius-project/samples/pull/1360.
