### ISSUE TITLE
Error in 'Test Samples' scheduled test run did not trigger Alert in Teams channel.

### ISSUE THREAD

**Issue by lakshmimsft** [radius-project/samples#896]
Samples Test Scheduled run has failed a couple times this week and a trigger has Not been raised in the Alerts channel:
eg. 

https://github.com/radius-project/samples/actions/runs/7183876029
https://github.com/radius-project/samples/actions/runs/7169888004.

Further context: An unusual incident occurred last week which may/may not be related: there was an Alert raised in the Teams channel for this issue:
https://github.com/radius-project/samples/issues/891
The link for logs within the issue opens up logs for a run that failed after the scheduled Test Samples run passed: https://github.com/radius-project/samples/actions/runs/7104964592

<img width="623" alt="image" src="https://github.com/radius-project/samples/assets/103459615/9600cc9c-21e8-4de7-842b-2544e6df0045">

Request to review rules/setup for alerts triggered by Samples repo test runs.

[AB#10741](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/10741)

**Comment by kachawla** [comment]
This will be fixed by https://github.com/radius-project/samples/pull/899

**Comment by ytimocin** [comment]
Can this be closed @lakshmimsft @kachawla?

**Comment by kachawla** [comment]
> Can this be closed @lakshmimsft @kachawla?

Yeah we should close this, @lakshmimsft please re-open if anything is still pending. Thanks for checking @ytimocin
