### ISSUE TITLE
Flaky test: `Failed to load resource: the server responded with a status of 503 (Service Unavailable)`

### ISSUE THREAD

**Issue by sk593** [radius-project/samples#907]
Seeing this on a few scheduled test runs for playwright tests 

```
Running 3 tests using 1 worker
Error text: "Failed to load resource: the server responded with a status of 503 (Service Unavailable)"
Error text: "Backend - status: 503, statusText: Service Unavailable, message: undefined"
Error text: "ERROR td"
```

[AB#10787](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/10787)

**Comment by ytimocin** [comment]
Closing this for now since I haven't run into this for a while now. Can reopen if I see this error.
