### ISSUE TITLE
"Existing application" tutorial failed since the container tag was removed from repository.

### ISSUE THREAD

**Issue by tanaka-takayoshi** [radius-project/samples#914]
The [existing application sample](https://github.com/radius-project/samples/blob/v0.28/samples/kubernetes/guestbook/deploy/frontend-deployment.yaml#L19) described in https://docs.radapp.io/tutorials/add-radius/
 refers `gcr.io/google-samples/gb-frontend:v4` image.

However, the tag was removed from the repository.

https://console.cloud.google.com/gcr/images/google-samples/GLOBAL/gb-frontend

A similar issue has been reported in kubernetes docs. https://github.com/kubernetes/website/issues/44224

I also tried to specify the sha256 tag like `gcr.io/google-samples/gb-frontend@sha256:e5233a1e2a6dc9c4ae1d1b754e3a3f62ecdc1da81b31422aff4e7390a0c6e534`, the deployed application failed since it can't connect to redis container.

[AB#10810](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/10810)

**Comment by willtsai** [comment]
@tanaka-takayoshi - I've made the changes to fix this by pulling a copy of the image from Radius' own registry. Hopefully this works for you now after pulling the latest from samples `v0.30` branch, please reopen this issue if not. Thanks!

p.s. docs page update PR is undergoing review as well: https://github.com/radius-project/docs/pull/1053
