### ISSUE TITLE
Automate upmerge PRs

### ISSUE THREAD

**Issue by AaronCrawfis** [radius-project/samples#931]
Today we have a manual process to "upmerge", or create a PR with all the changes, from the most recent versioned branch into the edge branch.

The reason we do this is because we want improvements to the samples to go into the versioned branch instead of into edge, so that end users don't have to wait a month to get the updates as part of the next release.

We need an automated process for this though, as the manual process is frequently forgotten.

We should:

1. Create a GitHub workflow that runs every Friday morning to create a PR from the default branch into the edge branch.
2. Add a workflow_dispatch trigger as well so it can be run manually if there's something important that needs to be upmerged

[AB#10876](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/10876)

**Comment by willtsai** [comment]
completed as a part of https://github.com/radius-project/samples/pull/1067
