### ISSUE TITLE
Flaky test - System.Net.Sockets.SocketException (104): Connection reset by peer

### ISSUE THREAD

**Issue by vinayada1** [radius-project/samples#957]
{
                  "code": "RecipeDeploymentFailed",
                  "message": "failed to deploy recipe default of type Applications.Datastores/redisCaches",
                  "details": [
                    {
                      "code": "DeploymentFailed",
                      "message": "At least one resource deployment operation failed. Please see the details for the specific operation that failed.",
                      "target": "/planes/radius/local/resourceGroups/default/providers/Microsoft.Resources/deployments/recipe170[67](https://github.com/radius-project/samples/actions/runs/7728654062/job/21069962754#step:18:68)16104352021281",
                      "details": [
                        {
                          "code": "ResourceDeploymentFailure",
                          "message": "An exception was encountered. Current deployment operation has failed. Error message: 'An error occurred while sending the request.'. Exception: 'System.IO.IOException: Unable to read data from the transport connection: Connection reset by peer.\n ---\u003e System.Net.Sockets.SocketException (104): Connection reset by peer\n   --- End of inner exception stack trace ---\n   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource\u003cSystem.Int32\u003e.GetResult(Int16 token)\n   at System.Net.Security.SslStream.EnsureFullTlsFrameAsync[TIOAdapter](TIOAdapter adapter)\n   at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](TIOAdapter adapter, Memory`1 buffer)\n   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)'",
                          "target": "/subscriptions/***/resourcegroups/rg-samplestest-7[72](https://github.com/radius-project/samples/actions/runs/7728654062/job/21069962754#step:18:73)8654062-1-eshop-azure/providers/Microsoft.Cache/redis/cache-zma2r7mqghpn4"
                        }
                      ]
                    }
                  ]
                }
              ]
            },

[AB#11065](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/11065)

**Comment by vinayada1** [comment]
Failure logs: [logs_7537 (1).zip](https://github.com/radius-project/samples/files/14116193/logs_7537.1.zip)

**Comment by ytimocin** [comment]
This issue is not on our end but on the responding server's end. Please see the message: `Connection reset by peer`. Closing this for now.
