### ISSUE TITLE
RDS purge action is broken (both purge and error handling)

### ISSUE THREAD

**Issue by AaronCrawfis** [radius-project/samples#963]
![image](https://github.com/radius-project/samples/assets/54363786/240c2eda-bf57-4c18-8205-3f763bff313e)

[AB#11135](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/11135)

**Comment by AaronCrawfis** [comment]
Looks like we:

- Didn't clone the repo. We need an actions/checkout@v4 step
- Didn't set an environment variable with the GitHub token. Error message above shows how to fix this

**Comment by willdavsmith** [comment]
Not sure how I didn't see this... PR here: https://github.com/radius-project/samples/pull/970

in the meantime I manually cleared the snapshots.
